export const conditions = {
    '0': {tiempo:"Soleado",icon:"./icons/clear-day.svg"},
    '1': {tiempo:"Escasa nubosidad",icon:"./icons/partly-cloudy-day.svg"},
    '2': {tiempo:"Escasa nubosidad",icon:"./icons/partly-cloudy-day.svg"},
    '3': {tiempo:"Nubosidad parcial",icon:"./icons/partly-cloudy-day.svg"},
    '4': {tiempo:"Mayormente nublado",icon:"./icons/overcast-day.svg"},
    '5': {tiempo:"Nublado",icon:"./icons/overcast.svg"},
    '6': {tiempo:"Niebla",icon:"./icons/fog-day.svg"},
    '7': {tiempo:"Niebla helada",icon:"./icons/fog.svg"},
    '10': {tiempo:"Lluvia leve",icon:"./icons/drizzle.svg"},
    '11': {tiempo:"Lluvia",icon:"./icons/rain.svg"},
    '12': {tiempo:"Lluvia intensa",icon:"./icons/rain.svg"},
    '13': {tiempo:"Lluvia gélida leve",icon:"./icons/sleet.svg"},
    '14': {tiempo:"Lluvia gélida",icon:"./icons/sleet.svg"},
    '15': {tiempo:"Lluvia gélida intensa",icon:"./icons/sleet.svg"},
    '16': {tiempo:"Llovizna",icon:"./icons/drizzle.svg"},
    '20': {tiempo:"Nieve leve",icon:"./icons/snow.svg"},
    '21': {tiempo:"Nieve",icon:"./icons/snow.svg"},
    '22': {tiempo:"Nieve intensa",icon:"./icons/snow.svg"},
    '30': {tiempo:"Aguanieve",icon:"./icons/sleet.svg"},
    '31': {tiempo:"Aguanieve",icon:"./icons/sleet.svg"},
    '32': {tiempo:"Aguanieve",icon:"./icons/sleet.svg"},
    '40': {tiempo:"Chubascos leves y localizados",icon:"./icons/partly-cloudy-day-drizzle.svg"},
    '41': {tiempo:"Chubascos localizados",icon:"./icons/partly-cloudy-day-rain.svg"},
    '42': {tiempo:"Chubascos intensos y localizados",icon:"./icons/partly-cloudy-day-rain.svg"},
    '43': {tiempo:"Chubascos leves",icon:"./icons/partly-cloudy-day-drizzle.svg"},
    '44': {tiempo:"Chubascos",icon:"./icons/partly-cloudy-day-rain.svg"},
    '45': {tiempo:"Chubascos intensos",icon:"./icons/partly-cloudy-day-rain.svg"},
    '46': {tiempo:"Chubascos leves y frecuentes",icon:"./icons/partly-cloudy-day-drizzle.svg"},
    '47': {tiempo:"Chubascos frecuentes",icon:"./icons/partly-cloudy-day-rain.svg"},
    '48': {tiempo:"Chubascos intensos y frecuentes",icon:"./icons/partly-cloudy-day-rain.svg"},
    '60': {tiempo:"Chubascos de nieve leves y localizados",icon:"./icons/partly-cloudy-night-snow.svg"},
    '61': {tiempo:"Chubascos de nieve localizados",icon:"./icons/partly-cloudy-night-snow.svg"},
    '62': {tiempo:"Chubascos de nieve intensos y localizados",icon:"./icons/partly-cloudy-night-snow.svg"},
    '63': {tiempo:"Chubascos de nieve leves",icon:"./icons/partly-cloudy-night-snow.svg"},
    '64': {tiempo:"Chubascos de nieve",icon:"./icons/partly-cloudy-night-snow.svg"},
    '65': {tiempo:"Chubascos de nieve intensos",icon:"./icons/partly-cloudy-night-snow.svg"},
    '66': {tiempo:"Chubascos de nieve leves y frecuentes",icon:"./icons/partly-cloudy-night-snow.svg"},
    '67': {tiempo:"Chubascos de nieve frecuentes",icon:"./icons/partly-cloudy-night-snow.svg"},
    '68': {tiempo:"Chubascos de nieve intensos y frecuentes",icon:"./icons/partly-cloudy-night-snow.svg"},
    '70': {tiempo:"Chubascos de aguanieve leves y localizados",icon:"./icons/partly-cloudy-night-sleet.svg"},
    '71': {tiempo:"Chubascos de aguanieve localizados",icon:"./icons/partly-cloudy-night-sleet.svg"},
    '72': {tiempo:"Chubascos de aguanieve intensos y localizados",icon:"./icons/partly-cloudy-night-sleet.svg"},
    '73': {tiempo:"Chubascos de aguanieve leves",icon:"./icons/partly-cloudy-night-sleet.svg"},
    '74': {tiempo:"Chubascos de aguanieve",icon:"./icons/partly-cloudy-night-sleet.svg"},
    '75': {tiempo:"Chubascos de aguanieve intensos",icon:"./icons/partly-cloudy-night-sleet.svg"},
    '76': {tiempo:"Chubascos de aguanieve leves y frecuentes",icon:"./icons/partly-cloudy-night-sleet.svg"},
    '77': {tiempo:"Chubascos de aguanieve frecuentes",icon:"./icons/partly-cloudy-night-sleet.svg"},
    '78': {tiempo:"Chubascos de aguanieve intensos y frecuentes",icon:"./icons/partly-cloudy-night-sleet.svg"},
    '100': {tiempo:"Tormentas leves y localizadas",icon:"./icons/thunderstorms-day-rain.svg"},
    '101': {tiempo:"Tormentas localizadas",icon:"./icons/thunderstorms-rain.svg"},
    '102': {tiempo:"Tormentas intensas y localizadas",icon:"./icons/thunderstorms-rain.svg"},
    '103': {tiempo:"Tormentas leves",icon:"./icons/thunderstorms-day-rain.svg"},
    '104': {tiempo:"Tormentas",icon:"./icons/thunderstorms-rain.svg"},
    '105': {tiempo:"Tormentas intensas",icon:"./icons/thunderstorms-rain.svg"},
    '106': {tiempo:"Tormentas leves y frecuentes",icon:"./icons/thunderstorms-day-rain.svg"},
    '107': {tiempo:"Tormentas frecuentes",icon:"./icons/thunderstorms-rain.svg"},
    '108': {tiempo:"Tormentas intensas y frecuentes",icon:"./icons/thunderstorms-rain.svg"},
    '120': {tiempo:"Tormentas de nieve leves y localizadas",icon:"./icons/thunderstorms-day-snow.svg"},
    '121': {tiempo:"Tormentas de nieve localizadas",icon:"./icons/thunderstorms-snow.svg"},
    '122': {tiempo:"Tormentas de nieve intensas y localizadas",icon:"./icons/thunderstorms-snow.svg"},
    '123': {tiempo:"Tormentas de nieve leves",icon:"./icons/thunderstorms-day-snow.svg"},
    '124': {tiempo:"Tormentas de nieve",icon:"./icons/thunderstorms-snow.svg"},
    '125': {tiempo:"Tormentas de nieve intensas",icon:"./icons/thunderstorms-snow.svg"},
    '126': {tiempo:"Tormentas de nieve leves y frecuentes",icon:"./icons/thunderstorms-day-snow.svg"},
    '127': {tiempo:"Tormentas de nieve frecuentes",icon:"./icons/thunderstorms-snow.svg"},
    '128': {tiempo:"Tormentas de nieve intensas y frecuentes",icon:"./icons/thunderstorms-snow.svg"},
    '130': {tiempo:"Tormentas de aguanieve leves y localizadas",icon:"./icons/thunderstorms-day-snow.svg"},
    '131': {tiempo:"Tormentas de aguanieve localizadas",icon:"./icons/thunderstorms-snow.svg"},
    '132': {tiempo:"Tormentas de aguanieve intensas y localizadas",icon:"./icons/thunderstorms-snow.svg"},
    '133': {tiempo:"Tormentas de aguanieve leves",icon:"./icons/thunderstorms-day-snow.svg"},
    '134': {tiempo:"Tormentas de aguanieve",icon:"./icons/thunderstorms-snow.svg"},
    '135': {tiempo:"Tormentas de aguanieve intensas",icon:"./icons/thunderstorms-snow.svg"},
    '136': {tiempo:"Tormentas de aguanieve leves y frecuentes",icon:"./icons/thunderstorms-day-snow.svg"},
    '137': {tiempo:"Tormentas de aguanieve frecuentes",icon:"./icons/thunderstorms-snow.svg"},
    '138': {tiempo:"Tormentas de aguanieve intensas y frecuentes",icon:"./icons/thunderstorms-snow.svg"},
    '140': {tiempo:"Lluvia tormentosa",icon:"./icons/thunderstorms-rain.svg"},
    '141': {tiempo:"Lluvia y nieve tormentosa",icon:"./icons/thunderstorms-snow.svg"},
    '142': {tiempo:"Nieve tormentosa",icon:"./icons/thunderstorms-snow.svg"},
    '210': {tiempo:"Lluvia leve intermitente",icon:"./icons/partly-cloudy-day-drizzle.svg"},
    '211': {tiempo:"Lluvia intermitente",icon:"./icons/partly-cloudy-day-drizzle.svg"},
    '212': {tiempo:"Lluvia intensa intermitente",icon:"./icons/partly-cloudy-day-drizzle.svg"},
    '220': {tiempo:"Nieve leve intermitente",icon:"./icons/partly-cloudy-day-snow.svg"},
    '221': {tiempo:"Nieve intermitente",icon:"./icons/partly-cloudy-day-snow.svg"},
    '222': {tiempo:"Nieve intensa intermitente",icon:"./icons/partly-cloudy-day-snow.svg"},
    '230': {tiempo:"Aguanieve leve intermitente",icon:"./icons/sleet.svg"},
    '231': {tiempo:"Aguanieve intermitente",icon:"./icons/sleet.svg"},
    '232': {tiempo:"Aguanieve intensa intermitente",icon:"./icons/sleet.svg"},
    '235': {tiempo:"Granizo",icon:"./icons/hail.svg"}    
}